3.1
zzzloba/SPBU_Homework_sem2 pull request #9
Opened 2019-03-03 00:06 UTC by zzzloba

2019-04-08 10:28 UTC, yurii-litvinov requested changes

2019-04-08 10:28 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/ArrayStackTests.cs
> +    [TestClass()]
У атрибутов, кстати, () можно не писать

2019-04-08 10:28 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/ListStackTests.cs
> +}
Тесты для стека на массивах и на списках по сути одинаковы, это же просто стеки. Так что надо побороть копипаст.

2019-04-08 10:28 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/PostfixCalculatorTests.cs
> +            }
Это долго и не думаю, что полезно. Я ж рассказывал на паре про факторизацию пространства входных данных на классы эквивалентности, внутри которых ожидаются одинаковые ошибки. Проверять надо только по одному представителю от каждого класса.

2019-04-10 10:27 UTC, yurii-litvinov requested changes
Определённо стало лучше, но можно ещё лучше (тесты на калькулятор более технологично можно сделать)

2019-04-10 10:27 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/PostfixCalculatorTests.cs
> +        /// Под "big"("bigger") подразумевается большая(больше) абсолютная величина
Это к чему? :)

2019-04-10 10:27 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/PostfixCalculatorTests.cs
> +        }
Это можно было сделать через `=>`, это же принципиально однострочный метод

2019-04-10 10:27 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/PostfixCalculatorTests.cs
> +        }
Есть же https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.datarowattribute?view=mstest-net-1.2.0

2019-04-10 10:27 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/StackTests.cs
> +        }
Можно через `=>`

2019-04-10 12:26 UTC, zzzloba commented on Lab3/Task1/Homework/HomeworkTests/PostfixCalculatorTests.cs
> +        /// Под "big"("bigger") подразумевается большая(больше) абсолютная величина
Когда писал названия методов, подумал, что таким же образом можно обозначать «большой» «больше» в отношении результата сравнений >,<. Почему-то показалось, что нужно уточнить значения big и bigger 🤣

2019-04-11 10:25 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/PostfixCalculatorTests.cs
> +        /// Под "big"("bigger") подразумевается большая(больше) абсолютная величина
Не, тут проблема в том, что summary --- это комментарий к следующему методу, а тут этот комментарий висит в воздухе :)

2019-04-11 10:26 UTC, yurii-litvinov approved these changes
Ага, зачтена

2019-04-11 10:26 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/PostfixCalculatorTests.cs
> +        }
Всё это же тожн можно через `=>` написать

2019-04-11 10:26 UTC, yurii-litvinov commented on Lab3/Task1/Homework/HomeworkTests/PostfixCalculatorTests.cs
> +            =>OneSubstractionTest(a, b, expected);
Ага, пробела не хватает

2019-04-11 18:29 UTC, merged